server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlite:./data/todo-app.sqlite
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:sqlite:/app/data/todo-app.sqlite
